In [1]:
import numpy as np
import pandas as pd

In [2]:
data =  pd.read_csv('C:\\Users\\KIIT\\Documents\\Python Scripts\\Pandas Assignment\\SalaryGender.csv')

In [3]:
data

Salary  Gender  Age  PhD
0    140.0       1   47    1
1     30.0       0   65    1
2     35.1       0   56    0
3     30.0       1   23    0
4     80.0       0   53    1
..     ...     ...  ...  ...
95    18.6       1   26    0
96   152.0       1   56    1
97     1.8       1   28    0
98    35.0       0   44    0
99     4.0       0   24    0

[100 rows x 4 columns]

In [4]:
df = pd.DataFrame(data)
df

Salary  Gender  Age  PhD
0    140.0       1   47    1
1     30.0       0   65    1
2     35.1       0   56    0
3     30.0       1   23    0
4     80.0       0   53    1
..     ...     ...  ...  ...
95    18.6       1   26    0
96   152.0       1   56    1
97     1.8       1   28    0
98    35.0       0   44    0
99     4.0       0   24    0

[100 rows x 4 columns]

In [5]:
df.columns

Index(['Salary', 'Gender', 'Age', 'PhD'], dtype='object')

In [6]:
salary = df['Salary']
npsal= np.array(salary)
npsal

array([140.  ,  30.  ,  35.1 ,  30.  ,  80.  ,  30.  ,  60.  ,  31.1 ,
       125.  ,  51.  ,   3.  ,  46.  , 150.  ,   3.  , 130.  ,  15.  ,
       130.  ,  84.  , 190.  ,  74.  ,  73.  ,  10.  ,  50.  ,   7.  ,
         9.5 ,  15.2 ,  28.6 ,  20.  ,  72.  ,  81.  , 100.  ,  90.  ,
        90.  ,  35.  ,  30.  ,  25.  ,  52.  ,   9.  ,  63.  ,  72.  ,
        16.  ,  92.  , 106.  ,   2.5 ,   9.  ,  32.  ,  32.  ,  55.  ,
        52.  ,  28.  ,  20.  ,  14.7 ,  22.3 ,  34.8 ,  84.  ,  19.  ,
       160.  ,  65.  ,  55.  ,   4.6 , 102.  ,  20.  ,  62.  ,  55.  ,
        45.6 ,  40.  ,  24.  ,  35.  ,  48.  ,  20.  ,  40.7 ,  15.  ,
         0.25, 152.  ,  39.8 ,  12.  ,  30.  , 120.  ,   1.7 ,  36.  ,
        96.  ,  38.  ,  90.  ,   9.  ,  25.8 ,  22.  ,  38.8 ,  72.  ,
        89.  ,  41.  ,  89.  ,  25.  ,  52.  , 115.  ,  66.  ,  18.6 ,
       152.  ,   1.8 ,  35.  ,   4.  ])

In [7]:
Gender = df['Gender']
npGen= np.array(Gender)
npGen

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0], dtype=int64)

In [8]:
age = df['Age']
npage= np.array(age)
npage

array([47, 65, 56, 23, 53, 27, 53, 30, 44, 63, 22, 59, 60, 28, 65, 25, 65,
       47, 66, 45, 46, 24, 60, 63, 27, 66, 36, 30, 51, 65, 45, 52, 54, 30,
       52, 26, 49, 22, 34, 60, 28, 58, 77, 67, 27, 48, 45, 49, 36, 65, 32,
       49, 67, 22, 49, 43, 61, 43, 52, 51, 66, 29, 62, 56, 61, 56, 41, 24,
       60, 43, 57, 23, 53, 71, 20, 27, 69, 58, 37, 32, 33, 32, 60, 71, 30,
       62, 54, 42, 62, 51, 71, 29, 55, 54, 55, 26, 56, 28, 44, 24],
      dtype=int64)

In [9]:
PhD = df['PhD']
npphd= np.array(PhD)
npphd

array([1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [10]:
Males = print(df['Gender'].tolist().count(1))
Females  = print(df['Gender'].tolist().count(0))

50
50


In [11]:
df2 = pd.DataFrame(df[['Age','PhD']])
df2

Age  PhD
0    47    1
1    65    1
2    56    0
3    23    0
4    53    1
..  ...  ...
95   26    0
96   56    1
97   28    0
98   44    0
99   24    0

[100 rows x 2 columns]

In [23]:
newdf=df[df.PhD>0]
newdf

Salary  Gender  Age  PhD
0    140.0       1   47    1
1     30.0       0   65    1
4     80.0       0   53    1
8    125.0       1   44    1
9     51.0       1   63    1
12   150.0       1   60    1
17    84.0       0   47    1
18   190.0       1   66    1
19    74.0       1   45    1
25    15.2       1   66    1
26    28.6       1   36    1
28    72.0       0   51    1
29    81.0       1   65    1
30   100.0       0   45    1
31    90.0       0   52    1
32    90.0       0   54    1
38    63.0       1   34    1
41    92.0       0   58    1
42   106.0       1   77    1
45    32.0       0   48    1
47    55.0       1   49    1
49    28.0       0   65    1
54    84.0       0   49    1
56   160.0       1   61    1
57    65.0       0   43    1
60   102.0       1   66    1
63    55.0       1   56    1
73   152.0       1   71    1
76    30.0       1   69    1
77   120.0       1   58    1
79    36.0       1   32    1
80    96.0       1   33    1
81    38.0       0   32    1
87    72.0       1   42    1
89    41.0       0   51    1
90    89.0       1   71    1
92    52.0       1   55    1
94    66.0       0   55    1
96   152.0       1   56    1

In [28]:
totalPhD = print(newdf['PhD'].tolist().count(1))

39


In [1]:
import numpy as np
a = np.array( [0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))


Original array:
[0 5 4 0 4 4 3 0 0 5 2 1 1 9]
Frequency of unique values of the said array:
[[0 1 2 3 4 5 9]
 [4 2 1 1 3 2 1]]


In [20]:
arr=np.array([[0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9,10, 11]])
arr = arr[arr > 4]
arr

array([ 5,  6,  7,  8,  9, 10, 11])

In [21]:
arr = np.array([np.nan, 1,2,np.nan,3,4,5])
print(arr)
print(arr[~np.isnan(arr)])


[nan  1.  2. nan  3.  4.  5.]
[1. 2. 3. 4. 5.]


In [27]:
x = np.random.randint(100,size=(10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[59 95 28 24 81 65 35 78  3 95]
 [96 88  6 41 56  3 22 42  9 41]
 [96  8  3  1 14 80 49 62 15 45]
 [73 96 45 55 48 97 66 56 86 38]
 [62 15 70 29 68 22 24  1 90 33]
 [36 73 79 65 48 37  9 91 35  7]
 [ 3  9 43 10 77 19 69 88 40 48]
 [65 11 65 73 62 23 91 66 42 28]
 [16 40 30 63  0 61 34 85 20 47]
 [14 19 76 76  8 86 77  8  7 30]]
Minimum and Maximum Values:
0 97


In [34]:
import numpy as np
x = np.random.randint(100,size=(30))
print("Original array:")
print(x)
y=x.mean()
print("MEAN:")
print(y)

Original array:
[63 52 97  6 29 83 91  8 27 31 75 27 92 21 34 25 90 47 58 67 65 62  3 56
 53  3 27 36 28 42]
MEAN:
46.6


In [41]:
arr=np.arange(11)
arr
negate = (arr > 3) & (arr < 9)
arr[negate] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [49]:
arr=np.array([[7,8,9],[4,5,2],[9,5,1]])
print(arr)
arrs=np.sort(arr,axis=0)
print("\n\nSorted array column wise: ",arrs)

[[7 8 9]
 [4 5 2]
 [9 5 1]]


Sorted array column wise:  [[4 5 1]
 [7 5 2]
 [9 8 9]]


In [67]:
arr = np.arange(0,16).reshape(4,4)
print(arr)
a=np.sum(arr[2],axis=0)
b=np.sum(arr[3],axis=0)
print("\n\n",a)
print("\n",b)
print("\nSum of last two rows are :",a+b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


 38

 54

Sum of last two rows are : 92


In [70]:
my_array = np.arange(16).reshape(4, 4)
print("Original array:")
print(my_array)
my_array[:,[0, 1]] = my_array[:,[1, 0]]
print("\nAfter swapping arrays:")
print(my_array)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

After swapping arrays:
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]
 [13 12 14 15]]


In [72]:
my_array = np.arange(16).reshape(4, 4)
print("Original array:")
print(my_array)
print("The Rank of a Matrix: ", np.linalg.matrix_rank(my_array))

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The Rank of a Matrix:  2
